# This is a basic workflow to help you get started with Actions

name: AWS

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          # Set always-auth in npmrc.
          always-auth: false # optional, default is false
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          # Set this option if you want the action to check for the latest available version that satisfies the version spec.
          check-latest: true
          # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKE
          # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
      - name: Install Compile Dependencies
        run: npm install --save screenshot-desktop
      - name: Install Build Dependencies
        run: npm install child_process
      - name: Compile App
        run: node app.js

      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: VM
      
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: ./screenshot.png
      
      

          
